name: firebase_chat_app
description: "Chat app"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.5.1
  go_router: ^13.2.2
  firebase_core: ^2.28.0
  firebase_auth: ^4.19.0
  cloud_firestore: ^4.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:


  uses-material-design: true

 