// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnGuRFH2TmpRRM-9XOG7rA9vsAKNhRcqQ',
    appId: '1:551223307025:web:1855824cfe4119bd83fab0',
    messagingSenderId: '551223307025',
    projectId: 'chat-4b9f1',
    authDomain: 'chat-4b9f1.firebaseapp.com',
    storageBucket: 'chat-4b9f1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyhnGeXSY2VSXvRSoIj2sYLcMt0N1ODVw',
    appId: '1:551223307025:android:67a1cc2e45e5748283fab0',
    messagingSenderId: '551223307025',
    projectId: 'chat-4b9f1',
    storageBucket: 'chat-4b9f1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPNTjV_sKpDicXE08jS4mR9ziNNrKLwUI',
    appId: '1:551223307025:ios:9539e0a94245583183fab0',
    messagingSenderId: '551223307025',
    projectId: 'chat-4b9f1',
    storageBucket: 'chat-4b9f1.appspot.com',
    iosBundleId: 'com.example.firebaseChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPNTjV_sKpDicXE08jS4mR9ziNNrKLwUI',
    appId: '1:551223307025:ios:629d02e5d65435d783fab0',
    messagingSenderId: '551223307025',
    projectId: 'chat-4b9f1',
    storageBucket: 'chat-4b9f1.appspot.com',
    iosBundleId: 'com.example.firebaseChatApp.RunnerTests',
  );
}
